
package view;

import dao.EncomendaDAO;
import database.ConnectionDB;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encomenda;


public class TelaGerencia extends javax.swing.JFrame {

    
    public TelaGerencia() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            loadTableCadastro();
            mostrarMostorista();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_gerencia = new javax.swing.JPanel();
        header_decorativo = new javax.swing.JPanel();
        header_texto = new javax.swing.JLabel();
        btn_voltar_gerencia = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_encomenda_gerencia = new javax.swing.JTable();
        label_origem_gerencia = new javax.swing.JLabel();
        combobox_origem_gerencia = new javax.swing.JComboBox<>();
        label_destino_gerencia = new javax.swing.JLabel();
        combobox_destino_gerencia = new javax.swing.JComboBox<>();
        label_posicao_gerencia = new javax.swing.JLabel();
        combobox_posicao_gerencia = new javax.swing.JComboBox<>();
        input_dataPost_gerencia = new javax.swing.JFormattedTextField();
        labelestimativa_gerencia = new javax.swing.JLabel();
        input_estimativa_gerencia = new javax.swing.JFormattedTextField();
        label_dataPost_gerencia = new javax.swing.JLabel();
        label_situacao_gerencia = new javax.swing.JLabel();
        combobox_situacao_gerencia = new javax.swing.JComboBox<>();
        label_chave_gerencia = new javax.swing.JLabel();
        btn_editar_gerencia = new javax.swing.JButton();
        btn_cadastrar_gerencia = new javax.swing.JButton();
        btn_salvar_gerencia = new javax.swing.JButton();
        btn_buscar_gerenciaa = new javax.swing.JButton();
        input_chave_gerencia = new javax.swing.JTextField();
        btn_gerarChave_adm = new javax.swing.JButton();
        label_userMotorista_gerencia = new javax.swing.JLabel();
        btn_deletar_gerencia = new javax.swing.JButton();
        combobox_motorista_gerencia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rastreio Express - Pianel de Gerência");
        setResizable(false);

        painel_gerencia.setBackground(new java.awt.Color(220, 220, 220));

        header_decorativo.setBackground(new java.awt.Color(21, 21, 21));

        header_texto.setBackground(new java.awt.Color(0, 0, 0));
        header_texto.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        header_texto.setForeground(new java.awt.Color(255, 255, 255));
        header_texto.setText(" Painel de Gerência");

        btn_voltar_gerencia.setBackground(new java.awt.Color(200, 200, 200));
        btn_voltar_gerencia.setForeground(new java.awt.Color(20, 20, 20));
        btn_voltar_gerencia.setText("Voltar ao Login");
        btn_voltar_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_gerenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_decorativoLayout = new javax.swing.GroupLayout(header_decorativo);
        header_decorativo.setLayout(header_decorativoLayout);
        header_decorativoLayout.setHorizontalGroup(
            header_decorativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_decorativoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(header_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar_gerencia)
                .addGap(30, 30, 30))
        );
        header_decorativoLayout.setVerticalGroup(
            header_decorativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_decorativoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(header_texto)
                .addGap(22, 22, 22))
            .addGroup(header_decorativoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_voltar_gerencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela_encomenda_gerencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entregra Prevista", "Status", "Motorista"
            }
        ));
        tabela_encomenda_gerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_encomenda_gerenciaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabela_encomenda_gerencia);

        label_origem_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_origem_gerencia.setText("Origem:");

        combobox_origem_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posição de partida", "Catalão", "Uberaba", "Uberlândia", "Goiânia" }));
        combobox_origem_gerencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        combobox_origem_gerencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_origem_gerenciaItemStateChanged(evt);
            }
        });

        label_destino_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_destino_gerencia.setText("Destino:");

        combobox_destino_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local de entrega", "Catalão", "Uberaba", "Uberlândia", "Goiânia" }));
        combobox_destino_gerencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        label_posicao_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_posicao_gerencia.setText("Posição:");

        combobox_posicao_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posição atual da encomenda", "Catalão", "Uberaba", "Uberlândia", "Goiânia", "Extravio", "Roubo", "Devolução" }));
        combobox_posicao_gerencia.setToolTipText("");
        combobox_posicao_gerencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        input_dataPost_gerencia.setForeground(new java.awt.Color(153, 153, 153));
        input_dataPost_gerencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        input_dataPost_gerencia.setToolTipText("dd / mm / yyyy");
        input_dataPost_gerencia.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        input_dataPost_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_dataPost_gerencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_dataPost_gerenciaFocusGained(evt);
            }
        });

        labelestimativa_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelestimativa_gerencia.setText("Data de Entrega:");

        input_estimativa_gerencia.setForeground(new java.awt.Color(20, 20, 20));
        input_estimativa_gerencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        input_estimativa_gerencia.setToolTipText("dd / mm / yyyy");
        input_estimativa_gerencia.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        input_estimativa_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_estimativa_gerencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_estimativa_gerenciaFocusGained(evt);
            }
        });

        label_dataPost_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_dataPost_gerencia.setText("Data de Postagem:");

        label_situacao_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_situacao_gerencia.setText("Situação:");

        combobox_situacao_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Situação atual da encomenda", "Ativo", "Interrompido", "Encerrado" }));
        combobox_situacao_gerencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        label_chave_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_chave_gerencia.setText("Chave de rastreio:");

        btn_editar_gerencia.setBackground(new java.awt.Color(20, 20, 20));
        btn_editar_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_editar_gerencia.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar_gerencia.setText("Editar");
        btn_editar_gerencia.setBorder(null);
        btn_editar_gerencia.setEnabled(false);
        btn_editar_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_gerenciaActionPerformed(evt);
            }
        });

        btn_cadastrar_gerencia.setBackground(new java.awt.Color(20, 20, 20));
        btn_cadastrar_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cadastrar_gerencia.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar_gerencia.setText("Cadastrar");
        btn_cadastrar_gerencia.setBorder(null);
        btn_cadastrar_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_gerenciaActionPerformed(evt);
            }
        });

        btn_salvar_gerencia.setBackground(new java.awt.Color(20, 20, 20));
        btn_salvar_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_salvar_gerencia.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar_gerencia.setText("Salvar");
        btn_salvar_gerencia.setBorder(null);
        btn_salvar_gerencia.setEnabled(false);
        btn_salvar_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_gerenciaActionPerformed(evt);
            }
        });

        btn_buscar_gerenciaa.setBackground(new java.awt.Color(20, 20, 20));
        btn_buscar_gerenciaa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar_gerenciaa.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar_gerenciaa.setText("Buscar");
        btn_buscar_gerenciaa.setBorder(null);
        btn_buscar_gerenciaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_gerenciaaActionPerformed(evt);
            }
        });

        input_chave_gerencia.setEditable(false);

        btn_gerarChave_adm.setText("Gerar");
        btn_gerarChave_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarChave_admActionPerformed(evt);
            }
        });

        label_userMotorista_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_userMotorista_gerencia.setText("User do Motorista:");

        btn_deletar_gerencia.setBackground(new java.awt.Color(20, 20, 20));
        btn_deletar_gerencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_deletar_gerencia.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletar_gerencia.setText("Deletar");
        btn_deletar_gerencia.setBorder(null);
        btn_deletar_gerencia.setEnabled(false);
        btn_deletar_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar_gerenciaActionPerformed(evt);
            }
        });

        combobox_motorista_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário do motorista" }));
        combobox_motorista_gerencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout painel_gerenciaLayout = new javax.swing.GroupLayout(painel_gerencia);
        painel_gerencia.setLayout(painel_gerenciaLayout);
        painel_gerenciaLayout.setHorizontalGroup(
            painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_decorativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_origem_gerencia)
                            .addComponent(combobox_origem_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_destino_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_destino_gerencia))
                        .addGap(18, 18, 18)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_posicao_gerencia)
                            .addComponent(combobox_posicao_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_situacao_gerencia)
                            .addComponent(combobox_situacao_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_gerenciaLayout.createSequentialGroup()
                                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_dataPost_gerencia)
                                    .addComponent(input_dataPost_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_estimativa_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelestimativa_gerencia)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_gerenciaLayout.createSequentialGroup()
                                .addComponent(label_userMotorista_gerencia)
                                .addGap(77, 77, 77))
                            .addComponent(combobox_motorista_gerencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_chave_gerencia)
                            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                                .addComponent(input_chave_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_gerarChave_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btn_cadastrar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_editar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_salvar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_deletar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar_gerenciaa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_gerenciaLayout.setVerticalGroup(
            painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addComponent(header_decorativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                                .addComponent(label_destino_gerencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_destino_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                                .addComponent(label_origem_gerencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_origem_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                                .addComponent(label_posicao_gerencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_posicao_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addComponent(label_situacao_gerencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox_situacao_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addComponent(label_dataPost_gerencia)
                        .addGap(5, 5, 5)
                        .addComponent(input_dataPost_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelestimativa_gerencia)
                            .addComponent(label_chave_gerencia))
                        .addGap(5, 5, 5)
                        .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_estimativa_gerencia)
                            .addComponent(input_chave_gerencia)
                            .addComponent(btn_gerarChave_adm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(label_userMotorista_gerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combobox_motorista_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_gerenciaa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletar_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painel_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_encomenda_gerenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_encomenda_gerenciaMouseClicked
        btn_editar_gerencia.setEnabled(true);
        btn_deletar_gerencia.setEnabled(true);
    }//GEN-LAST:event_tabela_encomenda_gerenciaMouseClicked

    private void combobox_origem_gerenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_origem_gerenciaItemStateChanged
        combobox_posicao_gerencia.setSelectedItem(combobox_origem_gerencia.getSelectedItem());
        combobox_posicao_gerencia.setEnabled(false);
        if(combobox_origem_gerencia.getSelectedIndex() == 0) {
            combobox_posicao_gerencia.setSelectedIndex(0);
            combobox_posicao_gerencia.setEnabled(true);
        }
    }//GEN-LAST:event_combobox_origem_gerenciaItemStateChanged

    private void input_dataPost_gerenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_dataPost_gerenciaFocusGained
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String currentDate = dateFormat.format(new Date());
            input_dataPost_gerencia.setForeground(new Color(20,20,20));
            input_dataPost_gerencia.setText(currentDate);
            input_dataPost_gerencia.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_input_dataPost_gerenciaFocusGained

    private void input_estimativa_gerenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_estimativa_gerenciaFocusGained
        try {

            if (input_dataPost_gerencia.getText().equals("Data de Postagem")) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                String currentDate = dateFormat.format(new Date());
                input_dataPost_gerencia.setForeground(new Color(20,20,20));
                input_dataPost_gerencia.setText(currentDate);
                input_dataPost_gerencia.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_input_estimativa_gerenciaFocusGained

    private void btn_editar_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_gerenciaActionPerformed
        btn_salvar_gerencia.setEnabled(true);
        try {
            int linha = tabela_encomenda_gerencia.getSelectedRow();

            combobox_origem_gerencia.setSelectedItem(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 1)));
            combobox_destino_gerencia.setSelectedItem(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 2)));
            combobox_posicao_gerencia.setSelectedItem(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 3)));
            combobox_posicao_gerencia.setEnabled(true);
            btn_gerarChave_adm.setEnabled(false);
            input_dataPost_gerencia.setText(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 4)));
            input_estimativa_gerencia.setText(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 5)));
            combobox_situacao_gerencia.setSelectedItem(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 6)));
            combobox_motorista_gerencia.setSelectedItem(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 7)));
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
            e.printStackTrace();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar tabela");
        }
    }//GEN-LAST:event_btn_editar_gerenciaActionPerformed

    private void btn_cadastrar_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_gerenciaActionPerformed
        if(input_chave_gerencia.getText().equals("") || combobox_origem_gerencia.getSelectedIndex() == 0|| combobox_destino_gerencia.getSelectedIndex() == 0|| combobox_posicao_gerencia.getSelectedIndex() == 0 || combobox_situacao_gerencia.getSelectedIndex() == 0 || input_dataPost_gerencia.getText().equals("") || input_estimativa_gerencia.getText().equals("") || combobox_motorista_gerencia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {
            try {
            
                String dataTexto = input_dataPost_gerencia.getText();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date dataPostagem = format.parse(dataTexto);

                String dataTexto1 = input_estimativa_gerencia.getText();
                Date dataEstimativa = format.parse(dataTexto1);
                if(dataEstimativa.getYear() < dataPostagem.getYear()) {
                    throw new InputMismatchException("Data Inválida");
                }else if (dataEstimativa.getYear() == dataPostagem.getYear()) {
                    if(dataEstimativa.getMonth() < dataPostagem.getMonth()) {
                        throw new InputMismatchException("Data Inválida");
                    }
                } else if ((dataEstimativa.getYear() == dataPostagem.getYear()) && (dataEstimativa.getMonth() == dataPostagem.getMonth())) {
                    System.out.print(dataEstimativa);
                    if(dataEstimativa.getDay()< dataPostagem.getDay()) {
                        System.out.print(dataEstimativa);
                        throw new InputMismatchException("Data Inválida");
                    }
                } 
                String chave = input_chave_gerencia.getText();
                
                Encomenda p = new Encomenda();
                p.setOrigem(String.valueOf(combobox_origem_gerencia.getSelectedItem()));
                p.setDestino(String.valueOf(combobox_destino_gerencia.getSelectedItem()));
                p.setPosicao(String.valueOf(combobox_posicao_gerencia.getSelectedItem()));
                p.setDataPostagem(dataPostagem);
                p.setDataEntrega(dataEstimativa);
                p.setStatus(String.valueOf(combobox_situacao_gerencia.getSelectedItem()));
                p.setChave(chave);
                p.setMotorista(combobox_motorista_gerencia.getSelectedItem().toString());


                EncomendaDAO.cadastrarEncomenda(p);
                input_chave_gerencia.setText("");
                input_dataPost_gerencia.setText("");
                input_dataPost_gerencia.setEnabled(true);
                input_estimativa_gerencia.setText("");
                combobox_motorista_gerencia.setSelectedIndex(1);

                combobox_origem_gerencia.setSelectedIndex(0);
                combobox_destino_gerencia.setSelectedIndex(0);
                combobox_posicao_gerencia.setSelectedIndex(0);
                combobox_situacao_gerencia.setSelectedIndex(0);
                combobox_posicao_gerencia.setEnabled(true);
                combobox_motorista_gerencia.setSelectedIndex(0);

                loadTableCadastro();
                         
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Formato de data inválido\nFormato correto: dd / mm / aaaa");
                System.err.println("Erro ao cadastrar encomenda: " + e);
            } catch (InputMismatchException e) { 
                JOptionPane.showMessageDialog(null, "Data de entrega inválida.");
                System.err.println(e);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro no cadastro");
                System.err.println("Erro ao cadastrar encomenda: " + e);
            }
        }
    }//GEN-LAST:event_btn_cadastrar_gerenciaActionPerformed

    private void btn_salvar_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_gerenciaActionPerformed
        try {
            
            if(combobox_origem_gerencia.getSelectedIndex() == 0|| combobox_destino_gerencia.getSelectedIndex() == 0|| combobox_posicao_gerencia.getSelectedIndex() == 0 || combobox_situacao_gerencia.getSelectedIndex() == 0 || input_dataPost_gerencia.getText().equals("") || input_estimativa_gerencia.getText().equals("") || combobox_motorista_gerencia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                int linha = tabela_encomenda_gerencia.getSelectedRow();
                int id = Integer.parseInt(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 0)));
                String dataTexto = input_dataPost_gerencia.getText();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date dataPostagem = format.parse(dataTexto);

                String dataTexto1 = input_estimativa_gerencia.getText();
                Date dataEstimativa = format.parse(dataTexto1);

                Encomenda p = new Encomenda();
                p.setId(id);
                p.setOrigem(combobox_origem_gerencia.getSelectedItem().toString());
                p.setDestino(combobox_destino_gerencia.getSelectedItem().toString());
                String selectedPosicao = String.valueOf(combobox_posicao_gerencia.getSelectedItem());
                p.setPosicao(selectedPosicao);
                p.setDataPostagem(dataPostagem);
                p.setDataEntrega(dataEstimativa);
                String selectedSituacao = String.valueOf(combobox_situacao_gerencia.getSelectedItem());
                p.setStatus(selectedSituacao);
                
                p.setMotorista(combobox_motorista_gerencia.getSelectedItem().toString());
               EncomendaDAO.atualizarEncomenda(p);
               combobox_origem_gerencia.setSelectedIndex(0);
               combobox_destino_gerencia.setSelectedIndex(0);
               combobox_posicao_gerencia.setSelectedIndex(0);
               combobox_posicao_gerencia.setEnabled(true);
               combobox_situacao_gerencia.setSelectedIndex(0);
               input_dataPost_gerencia.setText("");
               input_dataPost_gerencia.setEnabled(true);
               input_estimativa_gerencia.setText("");
               combobox_motorista_gerencia.setSelectedIndex(1);
               JOptionPane.showMessageDialog(null, "Encomenda atualizada com sucesso");
               loadTableCadastro();
               btn_salvar_gerencia.setEnabled(false);
               btn_editar_gerencia.setEnabled(false);
               btn_gerarChave_adm.setEnabled(true);
               combobox_motorista_gerencia.setSelectedIndex(0);

               
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela e clique em editar");
            e.printStackTrace();
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido.\n\nFormato válido: dd / mm / aaaa");
            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdministrativo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_salvar_gerenciaActionPerformed

    private void btn_buscar_gerenciaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_gerenciaaActionPerformed
        String chaveDigitada = JOptionPane.showInputDialog(null, "Insira a chave de rastreio da encomenda:");
        if(EncomendaDAO.validarChave(chaveDigitada)) {
            try {
                EncomendaDAO.buscarEncomenda(tabela_encomenda_gerencia, chaveDigitada);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chave de rastreio não encontrada");
            clearTableCadastro();
            try {
                loadTableCadastro();    
            } catch (Exception e) {
                e.printStackTrace();
            }
           
        }
    }//GEN-LAST:event_btn_buscar_gerenciaaActionPerformed

    private void btn_gerarChave_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarChave_admActionPerformed
        input_chave_gerencia.setText(Encomenda.geradorChave());

    }//GEN-LAST:event_btn_gerarChave_admActionPerformed

    private void btn_deletar_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar_gerenciaActionPerformed
        try {
            int linha = tabela_encomenda_gerencia.getSelectedRow();
            int confirmation = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja deletar essa encomenda?");
            if (confirmation == 0) {
                try {
                    int id = Integer.parseInt(String.valueOf(tabela_encomenda_gerencia.getValueAt(linha, 0)));
                    EncomendaDAO.deletarEncomenda(id);
                    JOptionPane.showMessageDialog(null, "Encomenda deletada com sucesso.");
                    loadTableCadastro();
                    btn_deletar_gerencia.setEnabled(false);
                    btn_editar_gerencia.setEnabled(false);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_deletar_gerenciaActionPerformed

    private void btn_voltar_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_gerenciaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar à tela de login?");
        
        if(confirm == 0) {
            this.setVisible(false);
            Loginview login = new Loginview();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btn_voltar_gerenciaActionPerformed

    public void loadTableCadastro() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entrega Prevista", "Status", "Motorista"}, 0);
        Connection a = ConnectionDB.getConnection();
        try {
            String query = "SELECT id, origem, destino, posicao, DATE_FORMAT(dataPostagem, '%d/%m/%Y') as dataFormatada, DATE_FORMAT(dataEntrega, '%d/%m/%Y') as dataFormatada2, status, motorista FROM ENCOMENDA ORDER BY id";
            Statement st = a.createStatement();
            ResultSet executeQuery = st.executeQuery(query);
            while (executeQuery.next()) { 
                Object linha[] = new Object[]{
                    executeQuery.getString("id"),
                    executeQuery.getString("origem"),
                    executeQuery.getString("destino"),
                    executeQuery.getString("posicao"),
                    executeQuery.getString("dataFormatada"), // Usando o alias definido na consulta
                    executeQuery.getString("dataFormatada2"),
                    executeQuery.getString("status"),
                    executeQuery.getString("motorista")
                };
                modelo.addRow(linha);
            }
            tabela_encomenda_gerencia.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
            }
    }
    
     public void clearTableCadastro() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entrega Prevista", "Status", "Motorista"}, 0);
        try {
            tabela_encomenda_gerencia.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerencia().setVisible(true);
            }
        });
    }
    
    public void mostrarMostorista() throws SQLException {
        Connection a = ConnectionDB.getConnection();
        String sql = "SELECT  * from usuario";
        try {
            Statement st = a.createStatement();
            ResultSet executeQuery = st.executeQuery(sql);
            while (executeQuery.next()) { 
                String nomeM = executeQuery.getString("usuario");
                combobox_motorista_gerencia.addItem(nomeM);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_gerenciaa;
    private javax.swing.JButton btn_cadastrar_gerencia;
    private javax.swing.JButton btn_deletar_gerencia;
    private javax.swing.JButton btn_editar_gerencia;
    private javax.swing.JButton btn_gerarChave_adm;
    private javax.swing.JButton btn_salvar_gerencia;
    private javax.swing.JButton btn_voltar_gerencia;
    private javax.swing.JComboBox<String> combobox_destino_gerencia;
    private javax.swing.JComboBox<String> combobox_motorista_gerencia;
    private javax.swing.JComboBox<String> combobox_origem_gerencia;
    private javax.swing.JComboBox<String> combobox_posicao_gerencia;
    private javax.swing.JComboBox<String> combobox_situacao_gerencia;
    private javax.swing.JPanel header_decorativo;
    private javax.swing.JLabel header_texto;
    private javax.swing.JTextField input_chave_gerencia;
    private javax.swing.JFormattedTextField input_dataPost_gerencia;
    private javax.swing.JFormattedTextField input_estimativa_gerencia;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_chave_gerencia;
    private javax.swing.JLabel label_dataPost_gerencia;
    private javax.swing.JLabel label_destino_gerencia;
    private javax.swing.JLabel label_origem_gerencia;
    private javax.swing.JLabel label_posicao_gerencia;
    private javax.swing.JLabel label_situacao_gerencia;
    private javax.swing.JLabel label_userMotorista_gerencia;
    private javax.swing.JLabel labelestimativa_gerencia;
    private javax.swing.JPanel painel_gerencia;
    private javax.swing.JTable tabela_encomenda_gerencia;
    // End of variables declaration//GEN-END:variables
}
