/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.ConnectionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author corin
 */
public class TelaRastreio extends javax.swing.JFrame {

    /**
     * Creates new form TelaRastreio
     */
    public TelaRastreio() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_gerencia = new javax.swing.JPanel();
        header_decorativo = new javax.swing.JPanel();
        header_texto = new javax.swing.JLabel();
        btn_voltar_rastreio = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_rastreio = new javax.swing.JTable();
        label_chave_rastreio = new javax.swing.JLabel();
        input_chave_rastreio = new javax.swing.JTextField();
        label_cod_rastreio = new javax.swing.JLabel();
        input_cod_rastreio = new javax.swing.JTextField();
        btn_buscar_rastreio = new javax.swing.JButton();
        btn_limpar_rastreio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rastreio Express - tela de rastreio");
        setResizable(false);

        painel_gerencia.setBackground(new java.awt.Color(220, 220, 220));

        header_decorativo.setBackground(new java.awt.Color(21, 21, 21));

        header_texto.setBackground(new java.awt.Color(0, 0, 0));
        header_texto.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        header_texto.setForeground(new java.awt.Color(255, 255, 255));
        header_texto.setText(" Rastreio Express - Painel de Rastreio");

        btn_voltar_rastreio.setBackground(new java.awt.Color(200, 200, 200));
        btn_voltar_rastreio.setForeground(new java.awt.Color(20, 20, 20));
        btn_voltar_rastreio.setText("Voltar ao Login");
        btn_voltar_rastreio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_rastreioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_decorativoLayout = new javax.swing.GroupLayout(header_decorativo);
        header_decorativo.setLayout(header_decorativoLayout);
        header_decorativoLayout.setHorizontalGroup(
            header_decorativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_decorativoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(header_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btn_voltar_rastreio)
                .addGap(25, 25, 25))
        );
        header_decorativoLayout.setVerticalGroup(
            header_decorativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_decorativoLayout.createSequentialGroup()
                .addGroup(header_decorativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header_decorativoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(header_texto))
                    .addGroup(header_decorativoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_voltar_rastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tabela_rastreio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entregra Prevista", "Status"
            }
        ));
        tabela_rastreio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_rastreioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabela_rastreio);

        label_chave_rastreio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_chave_rastreio.setText("Chave de rastreio:");

        label_cod_rastreio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_cod_rastreio.setText("Cód. da Encomenda");

        btn_buscar_rastreio.setBackground(new java.awt.Color(20, 20, 20));
        btn_buscar_rastreio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar_rastreio.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar_rastreio.setText("Buscar");
        btn_buscar_rastreio.setBorder(null);
        btn_buscar_rastreio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_rastreioActionPerformed(evt);
            }
        });

        btn_limpar_rastreio.setBackground(new java.awt.Color(20, 20, 20));
        btn_limpar_rastreio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_limpar_rastreio.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpar_rastreio.setText("Limpar");
        btn_limpar_rastreio.setBorder(null);
        btn_limpar_rastreio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_rastreioActionPerformed(evt);
            }
        });

        jLabel1.setText("Ou");

        javax.swing.GroupLayout painel_gerenciaLayout = new javax.swing.GroupLayout(painel_gerencia);
        painel_gerencia.setLayout(painel_gerenciaLayout);
        painel_gerenciaLayout.setHorizontalGroup(
            painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_decorativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addComponent(btn_buscar_rastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_limpar_rastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_cod_rastreio)
                    .addComponent(label_chave_rastreio)
                    .addComponent(input_chave_rastreio)
                    .addComponent(input_cod_rastreio)
                    .addGroup(painel_gerenciaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_gerenciaLayout.setVerticalGroup(
            painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_gerenciaLayout.createSequentialGroup()
                .addComponent(header_decorativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(label_chave_rastreio)
                .addGap(5, 5, 5)
                .addComponent(input_chave_rastreio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_cod_rastreio)
                .addGap(5, 5, 5)
                .addComponent(input_cod_rastreio)
                .addGap(47, 47, 47)
                .addGroup(painel_gerenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar_rastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpar_rastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painel_gerencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_rastreioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_rastreioMouseClicked
        
    }//GEN-LAST:event_tabela_rastreioMouseClicked

    private void btn_buscar_rastreioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_rastreioActionPerformed
        String chaveDigitada = input_chave_rastreio.getText();
        String codDigitado = input_cod_rastreio.getText();
        if (chaveDigitada.equals("") && codDigitado.equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a chave ou o código da encomenda");

        } else {
            clearTableRastrear();
            try {
                loadTableRastrear(chaveDigitada, codDigitado);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            input_chave_rastreio.setText("");
            input_cod_rastreio.setText("");
        }
        
    }//GEN-LAST:event_btn_buscar_rastreioActionPerformed

    private void btn_limpar_rastreioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_rastreioActionPerformed
        input_chave_rastreio.setText("");
        input_cod_rastreio.setText("");
        clearTableRastrear();
    }//GEN-LAST:event_btn_limpar_rastreioActionPerformed

    private void btn_voltar_rastreioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_rastreioActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar à tela de login?");

        if(confirm == 0) {
            this.setVisible(false);
            Loginview login = new Loginview();
            login.setVisible(true);
        }

    }//GEN-LAST:event_btn_voltar_rastreioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRastreio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRastreio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRastreio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRastreio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRastreio().setVisible(true);
            }
        });
        
    }
    
    public void clearTableRastrear() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entrega Prevista", "Status"}, 0);
        try {
            tabela_rastreio.setModel(modelo);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
public void loadTableRastrear(String chave, String cod) throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Origem", "Destino", "Posição", "Data de Postagem", "Entrega Prevista", "Status"}, 0);
        Connection a = ConnectionDB.getConnection();
        String sql = null;
        if(chave.equals("") && !(cod.equals(""))) {
            sql = "SELECT id, origem, destino, posicao, DATE_FORMAT(dataPostagem, '%d/%m/%Y') as dataFormatada, DATE_FORMAT(dataEntrega, '%d/%m/%Y') as dataFormatada2, status FROM ENCOMENDA where ID = " + cod + " ORDER BY id";
        } else if(cod.equals("") && !(chave.equals(""))) {
            sql = "SELECT id, origem, destino, posicao, DATE_FORMAT(dataPostagem, '%d/%m/%Y') as dataFormatada, DATE_FORMAT(dataEntrega, '%d/%m/%Y') as dataFormatada2, status FROM ENCOMENDA where CHAVE = '" + chave + "' ORDER BY id";
        } else {
            sql = "SELECT id, origem, destino, posicao, DATE_FORMAT(dataPostagem, '%d/%m/%Y') as dataFormatada, DATE_FORMAT(dataEntrega, '%d/%m/%Y') as dataFormatada2, status FROM ENCOMENDA where chave = '" + chave + "' or ID = " + cod + " ORDER BY id";
        }
        try {
            Statement st = a.createStatement();
            ResultSet executeQuery = st.executeQuery(sql);
            while (executeQuery.next()) { 
                Object linha[] = new Object[]{
                    executeQuery.getString("id"),
                    executeQuery.getString("origem"),
                    executeQuery.getString("destino"),
                    executeQuery.getString("posicao"),
                    executeQuery.getString("dataFormatada"), // Usando o alias definido na consulta
                    executeQuery.getString("dataFormatada2"),
                    executeQuery.getString("status"),
                };
                modelo.addRow(linha);
            }
            tabela_rastreio.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível buscar a Encomenda.");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_rastreio;
    private javax.swing.JButton btn_limpar_rastreio;
    private javax.swing.JButton btn_voltar_rastreio;
    private javax.swing.JPanel header_decorativo;
    private javax.swing.JLabel header_texto;
    private javax.swing.JTextField input_chave_rastreio;
    private javax.swing.JTextField input_cod_rastreio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_chave_rastreio;
    private javax.swing.JLabel label_cod_rastreio;
    private javax.swing.JPanel painel_gerencia;
    private javax.swing.JTable tabela_rastreio;
    // End of variables declaration//GEN-END:variables
}
